allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
minimumReleaseAgeExclude:
  - '@spartan-ng/cli@1.0.1'
  - '@spartan-ng/brain@1.0.1'
